package:
  name: pytorch
  version: "{{ environ.get('PYTORCH_BUILD_VERSION') }}"

source:
   git_url: https://github.com/pytorch/pytorch
   git_rev: "v{{ environ.get('PYTORCH_BUILD_VERSION') }}"

requirements:
  build:
    - cmake
    - {{ compiler('c') }} # [win]

  host:
    - python
    - numpy 1.11.*
    - setuptools
    - pyyaml
    - cffi
    - mkl >=2018
    - mkl-include
    - typing
    - ninja
    - magma-cuda80 # [not osx and not win]

  run:
    - python
    - numpy >=1.11
    - mkl >=2018
    - cffi
    - ninja
    - cudatoolkit =8 # [not osx and not win]
    - intel-openmp # [win]
    - mkl_fft # [win]

build:
  number: {{ environ.get('PYTORCH_BUILD_NUMBER') }}
  detect_binary_files_with_prefix: False
  string: py{{py}}_cuda{{ environ['CUDA_VERSION'] }}_cudnn{{ environ['CUDNN_VERSION'] }}_{{environ.get('PYTORCH_BUILD_NUMBER')}}
  features:
    - cuda80

test:
 requires:
    - cuda80
 imports:
    - torch
 source_files:
   - test
 commands:
   - python test/run_test.py


about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.