package:
  name: pytorch-nightly
  version: "{{ environ.get('PYTORCH_BUILD_VERSION') }}"

source:
   git_url: https://github.com/pytorch/pytorch
   git_rev: "nightly"

requirements:
  build:
    - cmake
    - {{ compiler('c') }} # [win]

  host:
    - python
    - numpy 1.11.*
    - setuptools
    - pyyaml
    - cffi
    - mkl >=2018
    - mkl-include
    - typing
    - ninja
    - magma-cuda90 # [not osx and not win]

  run:
    - python
    - numpy >=1.11
    - mkl >=2018
    - cffi
    - cudatoolkit =9 # [not osx and not win]

build:
  number: {{ environ.get('PYTORCH_BUILD_NUMBER') }}
  detect_binary_files_with_prefix: False
  string: py{{py}}_cuda{{ environ['CUDA_VERSION'] }}_cudnn{{ environ['CUDNN_VERSION'] }}_{{environ.get('PYTORCH_BUILD_NUMBER')}}
  features:
    - cuda90

test:
 requires:
    - cuda90
 imports:
    - torch
 source_files:
   - test
 commands:
   - OMP_NUM_THREADS=4 python ./test/run_test.py || true # [not win]
   - python ./test/run_test.py # [win]


about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.