package:
  name: pytorch
  version: "{{ environ.get('PYTORCH_BUILD_VERSION') }}"

source:
   path: ../pytorch-src

requirements:
  build:
    - python
    - numpy
    - setuptools
    - pyyaml
    - mkl-rt
    - magma-cuda75
    - gcc 4.8.5
  run:
    - python
    - numpy
    - mkl-rt

build:
  number: {{ environ.get('PYTORCH_BUILD_NUMBER') }}
  detect_binary_files_with_prefix: True
  binary_relocation: True
  rpaths:
    - lib/
    - {{ environ.get('SP_DIR') }}/torch/lib/

test:
  source_files:
    - test/common.py
    - test/common_nn.py
    - test/test_torch.py
    - test/test_autograd.py
    - test/test_nn.py
    - test/test_legacy_nn.py
    - test/test_cuda.py
    - test/test_multiprocessing.py
    - test/test_utils.py
    - test/run_test.sh
  commands:
    - ./test/run_test.sh

about:
  home: https://github.com/pytorch/pytorch
  license: BSD
  license_file: LICENSE