package:
  name: pytorch
  version: "{{ environ.get('PYTORCH_BUILD_VERSION') }}"

source:
  git_rev: v{{ environ.get('PYTORCH_BUILD_VERSION') }}
  git_url: https://github.com/pytorch/pytorch.git

requirements:
  build:
    - python
    - numpy
    - setuptools
    - pyyaml
    - mkl
  run:
    - python
    - pyyaml
    - numpy
    - mkl

build:
  number: {{ environ.get('PYTORCH_BUILD_NUMBER') }}
  detect_binary_files_with_prefix: true
  script: python setup.py install # [linux]
  script: MACOSX_DEPLOYMENT_TARGET=10.9 python setup.py install # [osx]

test:
  source_files:
    - test/common.py
    - test/common_nn.py
    - test/test_torch.py
    - test/test_autograd.py
    - test/test_nn.py
    - test/test_legacy_nn.py
    - test/test_cuda.py
    - test/run_test.sh
  commands:
    - ./test/run_test.sh

about:
  home: https://github.com/pytorch/pytorch
  license: BSD
  license_file: LICENSE