package:
  name: torchvision
  version: "{{ environ.get('PYTORCH_BUILD_VERSION') }}"

source:
   path: ../torchvision-src

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pillow
    - numpy
    - pytorch
    - six

build:
  number: {{ environ.get('PYTORCH_BUILD_NUMBER') }}
  script: python setup.py install

test:
   imports:
      - torchvision
      - torchvision.datasets
      - torchvision.transforms
about:
  home: https://github.com/pytorch/vision
  license: BSD
  license_file: LICENSE