package:
  name: pytorch
  version: "{{ environ.get('PYTORCH_BUILD_VERSION') }}"

source:
   path: ../pytorch-src

requirements:
  build:
    - python
    - numpy
    - setuptools
    - pyyaml
    - mkl
    - cffi
    - gcc # [not osx]
    - magma-cuda75 # [not osx]

  run:
    - python
    - numpy
    - mkl
    - cffi
    - libgcc # [not osx]
build:
  number: {{ environ.get('PYTORCH_BUILD_NUMBER') }}
  detect_binary_files_with_prefix: True
  binary_relocation: True
  rpaths:
    - lib/
    - {{ environ.get('SP_DIR') }}/torch/lib/

# test:
#  source_files:
#    - test
#  commands:
#    - ./test/run_test.sh


about:
  home: https://github.com/pytorch/pytorch
  license: BSD
  license_file: LICENSE